name: Vanubuntu Daily Build

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build ISOs
        run: sudo bash ./vanubuntu.sh flatpak gsconnect

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Vanubuntu x64 ISO
          path: |
            ./vanubuntu-x64.iso
